name: deploy myblog

on:
  push:
    branches:
      - 'main' # 针对 main 分支的 push 事件进行构建
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # 第三方的 action

      - name: set id_rsa # 设置私钥
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 47.110.87.219 >> ~/.ssh/known_hosts

      - name: deploy # 自动发布
        run: |
          ssh root@47.110.87.219 "
            # 注意：服务器已经 git clone 代码到 /root/myblog/imooc-320-server 目录下了

            cd /root/myblog/imooc-320-server;
            git checkout . ;
            git checkout main;
            git pull origin main; # 拉取最新代码

            # 重启服务
            npm install;
            npm run prd;
          "

      - name: delete id_rsa # 删除私钥
        run: rm -rf ~/.ssh/id_rsa
